export const tags: string[] = [
  "All",
  "Array",
  "Hash Table",
  "Brute Force",
  "Optimization",
  "Time Complexity",
  "Space Complexity",
  "JavaScript",
  "Python",
  "Java",
  "C++",
  "Interview Tips",
  "Edge Cases",
  "Follow-up Questions",
  "Similar Problems",
  "Algorithm Analysis",
  "Big O Notation",
  "One-pass Solution",
  "Two-pointer Technique",
  "Sorting Approach",
];

export const commentTags: string[] = [
  "array",
  "string",
  "hashmap",
  "dynamic programming",
  "recursion",
  "binary search",
  "linked list",
  "tree",
  "graph",
  "stack",
  "queue",
  "heap",
  "sorting",
  "greedy",
  "sliding window",
  "two pointers",
  "dfs",
  "bfs",
  "backtracking",
  "math",
  "bit manipulation",
  "matrix",
  "design",
  "trie",
  "dp",
  "topological sort",
  "prefix sum",
  "suffix sum",
  "monotonic stack",
  "heap sort",
  "merge sort",
  "quick sort",
  "counting sort",
  "radix sort",
  "bucket sort",
  "binary tree",
  "bst",
  "segment tree",
  "fenwick tree",
  "union find",
  "graph traversal",
  "dijkstra",
  "bellman ford",
  "floyd warshall",
  "kruskal",
  "prim",
  "shortest path",
  "longest path",
  "knapsack",
  "coin change",
  "word break",
  "palindrome",
  "subarray",
  "subsequence",
  "permutation",
  "combination",
  "heapify",
  "priority queue",
  "hashset",
  "hashmap collision",
  "LRU cache",
  "memoization",
  "tabulation",
  "recursion tree",
  "dynamic array",
  "circular queue",
  "deque",
  "sliding window max",
  "binary search tree",
  "balanced bst",
  "graph coloring",
  "top k",
  "median",
  "union find path compression",
  "kruskal mst",
  "prim mst",
  "floyd warshall shortest path",
  "stack overflow",
  "tree traversal",
  "preorder traversal",
  "inorder traversal",
  "postorder traversal",
  "level order traversal",
  "bfs shortest path",
  "dfs longest path",
  "graph cycle detection",
  "strongly connected components",
  "tarjan",
  "kosaraju",
  "top down dp",
  "bottom up dp",
  "bitmask dp",
  "meet in the middle",
  "divide and conquer",
  "fast exponentiation",
  "modular arithmetic",
  "combinatorics",
  "matrix exponentiation",
  "fibonacci",
  "catalan numbers",
  "pascal triangle",
  "prime numbers",
  "sieve of eratosthenes",
  "gcd",
  "lcm",
  "mod inverse",
  "extended euclidean",
  "number theory",
  "geometry",
  "convex hull",
  "line sweep",
  "interval",
  "segment tree lazy",
  "fenwick tree 2d",
  "range sum",
  "range update",
  "range minimum query",
  "range maximum query",
  "disjoint set",
  "graph representation",
  "adjacency list",
  "adjacency matrix",
  "edge list",
  "weighted graph",
  "unweighted graph",
  "directed graph",
  "undirected graph",
  "cycle detection",
  "top k frequent",
  "sliding window sum",
  "substring",
  "subsequence sum",
  "subsequence count",
  "palindrome partition",
  "expression evaluation",
  "stack evaluation",
  "queue simulation",
  "priority queue simulation",
  "heap simulation",
  "tree diameter",
  "tree height",
  "tree depth",
  "tree balance",
  "tree flatten",
  "graph bfs level",
  "graph dfs path",
  "connected components",
  "bridges",
  "articulation points",
  "mst",
  "shortest path dijkstra",
  "shortest path bellman",
  "shortest path floyd",
  "shortest path bfs",
  "max flow",
  "min cut",
  "ford fulkerson",
  "edmonds karp",
  "push relabel",
  "network flow",
  "bipartite check",
  "bipartite matching",
  "hungarian algorithm",
  "max matching",
  "dfs backtracking",
  "dfs with memoization",
  "bfs shortest",
  "bfs longest",
  "topological sort kahn",
  "topological sort dfs",
  "cycle detection dfs",
  "cycle detection union find",
  "strongly connected component tarjan",
  "strongly connected component kosaraju",
  "tree dp",
  "tree diameter dp",
  "tree path sum",
  "lowest common ancestor",
  "binary lifting",
  "lca",
  "range query",
  "range update query",
  "fenwick tree point update",
  "fenwick tree range update",
  "segment tree point update",
  "segment tree range update",
  "lazy propagation",
  "interval tree",
  "kmp",
  "rabin karp",
  "z algorithm",
  "manacher",
  "suffix array",
  "suffix tree",
  "trie insert",
  "trie search",
  "aho corasick",
  "rolling hash",
  "hashing",
  "modular hash",
  "hash collision",
  "string matching",
  "pattern matching",
  "regex",
  "wildcard matching",
  "edit distance",
  "levenshtein",
  "longest common subsequence",
  "longest common substring",
  "palindromic substring",
  "palindromic subsequence",
  "longest increasing subsequence",
  "longest decreasing subsequence",
  "subsequence sum",
  "subarray sum",
  "maximum subarray",
  "kadane",
  "minimum subarray",
  "sliding window minimum",
  "sliding window maximum",
  "window sum",
  "two pointer technique",
  "three pointer",
  "meet in the middle",
  "binary search upper bound",
  "binary search lower bound",
  "ternary search",
  "exponential search",
  "jump search",
  "interpolation search",
  "fibonacci search",
  "sqrt decomposition",
  "mo’s algorithm",
  "sparse table",
  "range minimum query",
  "range maximum query",
  "range gcd query",
  "range sum query",
  "prefix xor",
  "suffix xor",
  "bitset",
  "bitmasking",
  "subset generation",
  "combinations generation",
  "permutations generation",
  "heap operations",
  "priority queue operations",
  "stack operations",
  "queue operations",
  "deque operations",
  "linked list operations",
  "hashmap operations",
  "hashset operations",
  "graph operations",
  "matrix operations",
  "vector operations",
  "list operations",
  "set operations",
  "map operations",
  "dict operations",
  "dict comprehension",
  "list comprehension",
  "generator expression",
  "recursion tree analysis",
  "time complexity analysis",
  "space complexity analysis",
  "big o notation",
  "amortized analysis",
  "probability",
  "expected value",
  "variance",
  "randomized algorithms",
  "monte carlo",
  "simulated annealing",
  "genetic algorithms",
  "backtracking n queen",
  "sudoku solver",
  "word search",
  "crossword solver",
  "maze solver",
  "flood fill",
  "connected components dfs",
  "connected components bfs",
  "top k elements heap",
  "median heap",
  "sliding window median",
  "sliding window frequency",
  "counting sort optimization",
  "bucket sort optimization",
  "radix sort optimization",
  "merge k sorted arrays",
  "merge k sorted lists",
  "interval merge",
  "interval overlap",
  "interval scheduling",
  "activity selection",
  "job sequencing",
  "fractional knapsack",
  "0 1 knapsack",
  "unbounded knapsack",
  "bounded knapsack",
  "subset sum",
  "partition equal subset sum",
  "minimum coins",
  "coin change",
  "coin change permutations",
  "coin change combinations",
  "string compression",
  "run length encoding",
  "lru cache design",
  "lfu cache design",
  "stack min design",
  "queue with two stacks",
  "queue with max",
  "circular buffer",
  "ring buffer",
  "deque design",
  "stack design",
  "queue design",
  "hashmap design",
  "hashset design",
  "trie design",
  "binary search tree design",
  "avl tree",
  "red black tree",
  "splay tree",
  "treap",
  "skip list",
  "segment tree design",
  "fenwick tree design",
  "disjoint set design",
  "union find design",
  "graph design",
  "weighted graph design",
  "directed graph design",
  "undirected graph design",
  "graph traversal design",
  "dfs design",
  "bfs design",
  "topological sort design",
  "mst design",
  "flow network",
  "network flow design",
  "max flow design",
  "min cut design",
  "edmonds karp design",
  "ford fulkerson design",
  "hungarian design",
  "graph coloring design",
  "bipartite graph design",
  "strongly connected component design",
  "tarjan design",
  "kosaraju design",
  "matrix traversal",
  "matrix rotation",
  "matrix flipping",
  "matrix transpose",
  "matrix multiplication",
  "matrix chain multiplication",
  "strassen algorithm",
  "divide and conquer design",
  "dynamic programming design",
  "memoization design",
  "tabulation design",
  "space optimization dp",
  "dp with bitmask",
  "dp on trees",
  "dp on graphs",
  "dp on strings",
  "dp on grids",
  "dp on subsequences",
  "dp on subarrays",
  "dp on intervals",
  "dp optimization",
  "convex hull trick",
  "slope trick",
  "monotonic queue",
  "monotonic stack design",
  "sliding window optimization",
  "two pointer optimization",
  "meet in the middle optimization",
  "binary search optimization",
  "ternary search optimization",
  "sqrt decomposition optimization",
  "mo’s algorithm optimization",
  "sparse table optimization",
  "range query optimization",
  "lazy propagation optimization",
  "segment tree optimization",
  "fenwick tree optimization",
  "matrix exponentiation optimization",
  "fast exponentiation",
  "modular exponentiation",
  "prime sieve optimization",
  "gcd optimization",
  "lcm optimization",
  "extended euclidean",
  "mod inverse optimization",
  "number theory design",
  "geometry design",
  "convex hull design",
  "line sweep design",
  "interval design",
  "collision detection",
  "rectangle overlap",
  "circle overlap",
  "polygon area",
  "trapezoid area",
  "triangle area",
  "circle area",
  "point in polygon",
  "line intersection",
  "ray casting",
  "vector operations",
  "dot product",
  "cross product",
  "vector magnitude",
  "vector normalization",
  "angle between vectors",
  "rotation matrix",
  "reflection matrix",
  "scaling matrix",
  "translation matrix",
  "shear matrix",
  "graph visualization",
  "tree visualization",
  "matrix visualization",
  "array visualization",
  "linked list visualization",
  "stack visualization",
  "queue visualization",
  "heap visualization",
  "priority queue visualization",
  "trie visualization",
  "dynamic programming visualization",
  "recursion visualization",
  "backtracking visualization",
  "graph traversal visualization",
  "algorithm visualization",
  "sorting visualization",
  "searching visualization",
  "binary search visualization",
  "dfs visualization",
  "bfs visualization",
  "shortest path visualization",
  "longest path visualization",
  "tree dp visualization",
  "matrix dp visualization",
  "bitmask dp visualization",
  "game theory",
  "minimax",
  "alpha beta pruning",
  "nim game",
  "sprague grundy theorem",
  "combinatorial game",
  "graph game",
  "matrix game",
  "probability game",
  "expected value game",
  "randomized game",
  "monte carlo simulation",
  "simulation",
  "queue simulation",
  "stack simulation",
  "heap simulation",
  "tree simulation",
  "graph simulation",
  "network simulation",
  "flow simulation",
  "pathfinding simulation",
  "astar algorithm",
  "greedy algorithm",
  "greedy proof",
  "divide and conquer algorithm",
  "dynamic programming algorithm",
  "recursion algorithm",
  "backtracking algorithm",
  "brute force",
  "optimization",
  "approximation algorithm",
  "heuristics",
  "genetic algorithm",
  "simulated annealing algorithm",
  "randomized algorithm",
  "hashing algorithm",
  "string hashing",
  "rolling hash algorithm",
  "rabin karp algorithm",
  "kmp algorithm",
  "z algorithm",
  "manacher algorithm",
  "suffix array algorithm",
  "suffix tree algorithm",
  "aho corasick algorithm",
  "graph algorithm",
  "mst algorithm",
  "dijkstra algorithm",
  "bellman ford algorithm",
  "floyd warshall algorithm",
  "kruskal algorithm",
  "prim algorithm",
  "topological sort algorithm",
  "tarjan algorithm",
  "kosaraju algorithm",
  "dfs algorithm",
  "bfs algorithm",
  "shortest path algorithm",
  "longest path algorithm",
  "max flow algorithm",
  "min cut algorithm",
  "edmonds karp algorithm",
  "ford fulkerson algorithm",
  "hungarian algorithm",
  "stack algorithm",
  "queue algorithm",
  "heap algorithm",
  "linked list algorithm",
  "tree algorithm",
  "binary search tree algorithm",
  "trie algorithm",
  "segment tree algorithm",
  "fenwick tree algorithm",
  "disjoint set algorithm",
  "union find algorithm",
  "matrix algorithm",
  "geometry algorithm",
  "number theory algorithm",
  "combinatorics algorithm",
  "probability algorithm",
  "simulation algorithm",
  "game theory algorithm",
  "design patterns",
  "singleton",
  "factory",
  "builder",
  "observer",
  "strategy",
  "adapter",
  "decorator",
  "composite",
  "bridge",
  "proxy",
  "command",
  "mediator",
  "state",
  "visitor",
  "iterator",
  "template method",
  "chain of responsibility",
  "flyweight",
  "memento",
  "facade",
  "prototype",
  "dependency injection",
  "mvc",
  "mvvm",
  "clean architecture",
  "hexagonal architecture",
  "cqrs",
  "event sourcing",
  "microservices",
  "service oriented architecture",
  "rest api",
  "graphql api",
  "websocket",
  "socket io",
  "rpc",
  "grpc",
  "api design",
  "database design",
  "sql",
  "nosql",
  "mongodb",
  "postgresql",
  "mysql",
  "sqlite",
  "redis",
  "cassandra",
  "dynamodb",
  "elasticsearch",
  "indexing",
  "query optimization",
  "normalization",
  "denormalization",
  "transactions",
  "locking",
  "concurrency",
  "threading",
  "multithreading",
  "parallelism",
  "asynchronous programming",
  "promises",
  "async await",
  "callback",
  "event loop",
  "react",
  "react hooks",
  "react redux",
  "react router",
  "react context",
  "react query",
  "nextjs",
  "vue",
  "angular",
  "svelte",
  "tailwind",
  "material ui",
  "chakra ui",
  "shadcn ui",
  "css",
  "html",
  "javascript",
  "typescript",
  "python",
  "java",
  "c++",
  "c",
  "c#",
  "ruby",
  "php",
  "go",
  "rust",
  "kotlin",
  "swift",
  "dart",
  "flutter",
  "android",
  "ios",
  "backend",
  "frontend",
  "fullstack",
  "devops",
  "docker",
  "kubernetes",
  "aws",
  "azure",
  "gcp",
  "ci cd",
  "jenkins",
  "github actions",
  "unit testing",
  "integration testing",
  "e2e testing",
  "jest",
  "mocha",
  "chai",
  "enzyme",
  "cypress",
  "playwright",
  "selenium",
  "tdd",
  "bdd",
  "mocking",
  "stubbing",
  "coverage",
  "performance",
  "profiling",
  "logging",
  "monitoring",
  "alerting",
  "sentry",
  "new relic",
  "datadog",
  "prometheus",
  "grafana",
  "elastic stack",
  "kibana",
  "nginx",
  "apache",
  "load balancing",
  "caching",
  "memcached",
  "redis cache",
  "cdn",
  "cloudfront",
  "fastly",
  "akamai",
  "security",
  "authentication",
  "authorization",
  "oauth",
  "jwt",
  "csrf",
  "xss",
  "sql injection",
  "hashing",
  "encryption",
  "ssl",
  "tls",
  "rsa",
  "aes",
  "sha256",
  "md5",
  "bcrypt",
  "argon2",
  "scrypt",
  "tokenization",
  "captcha",
  "recaptcha",
  "rate limiting",
  "throttling",
  "pagination",
  "lazy loading",
  "infinite scroll",
  "virtual scroll",
  "react virtualized",
  "react window",
  "responsive design",
  "mobile first",
  "progressive web app",
  "pwa",
  "seo",
  "a11y",
  "aria",
  "internationalization",
  "localization",
  "i18n",
  "l10n",
  "color theory",
  "typography",
  "ux",
  "ui",
  "design system",
  "storybook",
  "figma",
  "adobe xd",
  "sketch",
  "canva",
  "animation",
  "framer motion",
  "lottie",
  "three js",
  "d3 js",
  "chart js",
  "recharts",
  "highcharts",
  "data visualization",
  "analytics",
  "google analytics",
  "mixpanel",
  "segment",
  "big o notation",
  "time complexity",
  "space complexity",
  "optimization techniques",
  "dynamic programming patterns",
  "greedy patterns",
  "divide and conquer patterns",
  "sliding window patterns",
  "two pointers patterns",
  "dfs patterns",
  "bfs patterns",
  "backtracking patterns",
  "graph patterns",
  "tree patterns",
  "matrix patterns",
  "array patterns",
  "string patterns",
  "bit manipulation patterns",
  "math patterns",
  "geometry patterns",
  "number theory patterns",
  "combinatorics patterns",
  "probability patterns",
  "simulation patterns",
  "game theory patterns",
  "design patterns practice",
  "system design practice",
  "coding interview",
  "leetcode",
  "hackerrank",
  "codeforces",
  "codechef",
  "atcoder",
  "interviewbit",
  "geeksforgeeks",
  "competitive programming",
  "mock interview",
  "pair programming",
  "code review",
  "github",
  "git",
  "version control",
  "branching",
  "merging",
  "rebasing",
  "cherry pick",
  "pull request",
  "code commit",
  "commit message",
  "semantic commit",
  "feature branch",
  "hotfix branch",
  "release branch",
  "agile",
  "sprint",
  "scrum",
  "kanban",
  "standup",
  "retro",
  "jira",
  "trello",
  "asana",
  "notion",
  "productivity",
  "time management",
  "pomodoro",
  "focus",
  "deep work",
  "habit tracking",
  "goal setting",
  "learning",
  "self improvement",
  "career",
  "resume",
  "portfolio",
  "mockup",
  "cv",
  "linkedin",
  "job interview",
  "coding interview prep",
  "data structures",
  "algorithms",
  "optimization",
  "logic",
  "reasoning",
  "problem solving",
  "critical thinking",
  "analytical skills",
  "debugging",
  "troubleshooting",
  "refactoring",
  "clean code",
  "code smells",
  "unit test",
  "integration test",
  "test driven development",
  "behavior driven development",
  "software engineering",
  "computer science",
  "artificial intelligence",
  "machine learning",
  "deep learning",
  "neural networks",
  "natural language processing",
  "nlp",
  "computer vision",
  "cv",
  "reinforcement learning",
  "supervised learning",
  "unsupervised learning",
  "semi supervised learning",
  "transfer learning",
  "tensorflow",
  "pytorch",
  "scikit learn",
  "keras",
  "xgboost",
  "lightgbm",
  "catboost",
  "pandas",
  "numpy",
  "matplotlib",
  "seaborn",
  "plotly",
  "data analysis",
  "data preprocessing",
  "feature engineering",
  "feature selection",
  "model evaluation",
  "cross validation",
  "grid search",
  "hyperparameter tuning",
  "model deployment",
  "flask",
  "fastapi",
  "django",
  "express",
  "nodejs",
  "spring boot",
  "rest api development",
  "graphql api development",
  "websocket programming",
  "socket programming",
  "tcp",
  "udp",
  "http",
  "https",
  "ssl tls",
  "api authentication",
  "api authorization",
  "jwt authentication",
  "oauth2",
  "openid connect",
  "cookie",
  "session management",
  "state management",
  "redux",
  "mobx",
  "zustand",
  "recoil",
  "context api",
  "react query",
  "swr",
  "apollo client",
  "graphql server",
  "prisma",
  "typeorm",
  "mongoose",
  "sequelize",
  "postgresql design",
  "mysql design",
  "mongodb design",
  "redis design",
  "cassandra design",
  "elasticsearch design",
  "dockerization",
  "docker compose",
  "kubernetes deployment",
  "helm",
  "terraform",
  "ansible",
  "ci cd pipeline",
  "github actions ci cd",
  "gitlab ci cd",
  "jenkins ci cd",
  "cloud deployment",
  "aws ec2",
  "aws lambda",
  "aws s3",
  "aws rds",
  "aws dynamodb",
  "aws sns",
  "aws sqs",
  "gcp app engine",
  "gcp cloud functions",
  "azure functions",
  "azure web apps",
  "serverless architecture",
  "microservices architecture",
  "event driven architecture",
  "message queue",
  "rabbitmq",
  "kafka",
  "pub sub",
  "stream processing",
  "data pipeline",
  "etl",
  "spark",
  "hadoop",
  "airflow",
  "prefect",
  "workflow automation",
  "monitoring",
  "logging",
  "prometheus",
  "grafana",
  "new relic",
  "datadog",
  "sentry",
  "alerting",
  "error tracking",
  "exception handling",
  "performance tuning",
  "profiling",
  "benchmarking",
  "stress testing",
  "load testing",
  "scalability",
  "high availability",
  "fault tolerance",
  "distributed systems",
  "consensus algorithms",
  "paxos",
  "raft",
  "leader election",
  "sharding",
  "replication",
  "partitioning",
  "caching strategies",
  "cache invalidation",
  "cache eviction",
  "memory management",
  "garbage collection",
  "concurrency control",
  "mutex",
  "semaphore",
  "lock free",
  "thread safe",
  "race condition",
  "deadlock",
  "livelock",
  "starvation",
  "thread pool",
  "async programming",
  "await",
  "promise",
  "callback",
  "event loop",
  "reactivity",
  "observer pattern",
  "pub sub pattern",
  "event emitter",
  "functional programming",
  "immutable data",
  "recursion",
  "tail recursion",
  "currying",
  "partial application",
  "map reduce",
  "stream processing",
  "lazy evaluation",
  "memoization",
  "dynamic dispatch",
  "polymorphism",
  "inheritance",
  "encapsulation",
  "abstraction",
  "composition",
  "aggregation",
  "association",
  "dependency injection",
  "interface segregation",
  "single responsibility",
  "open closed",
  "liskov substitution",
  "dependency inversion",
  "design principles",
  "solid principles",
  "clean architecture principles",
  "hexagonal architecture principles",
  "cqrs principles",
  "event sourcing principles",
  "ddd principles",
  "tdd principles",
  "bdd principles",
  "mocking",
  "stubbing",
  "test coverage",
  "unit testing framework",
  "integration testing framework",
  "e2e testing framework",
  "selenium testing",
  "cypress testing",
  "playwright testing",
  "jest testing",
  "mocha testing",
  "chai assertion",
  "enzyme testing",
  "react testing library",
  "storybook ui testing",
  "visual regression",
  "accessibility",
  "aria",
  "screen reader",
  "keyboard navigation",
  "contrast ratio",
  "color accessibility",
  "responsive design",
  "mobile first design",
  "media queries",
  "flexbox",
  "grid layout",
  "css variables",
  "css transitions",
  "css animations",
  "keyframes",
  "transform",
  "translate",
  "rotate",
  "scale",
  "skew",
  "3d transform",
  "perspective",
  "z index",
  "positioning",
  "absolute",
  "relative",
  "fixed",
  "sticky",
  "overflow",
  "scroll",
  "clip",
  "mask",
  "svg",
  "canvas",
  "webgl",
  "three js",
  "d3 js",
  "chart js",
  "recharts",
  "highcharts",
  "plotly",
  "data visualization",
  "analytics",
  "google analytics",
  "mixpanel",
  "segment",
  "user tracking",
  "funnel analysis",
  "event tracking",
  "conversion rate",
  "a b testing",
  "experimentation",
  "growth hacking",
  "seo",
  "page speed",
  "performance optimization",
  "lazy loading",
  "code splitting",
  "tree shaking",
  "bundle analysis",
  "webpack",
  "vite",
  "rollup",
  "esbuild",
  "babel",
  "typescript",
  "eslint",
  "prettier",
  "linting",
  "formatting",
  "commit hooks",
  "husky",
  "lint staged",
  "monorepo",
  "lerna",
  "pnpm",
  "yarn workspaces",
  "npm workspaces",
  "versioning",
  "semantic versioning",
  "changelog",
  "documentation",
  "readme",
  "mdx",
  "storybooks",
  "component library",
  "design system",
  "ui kit",
  "theme provider",
  "dark mode",
  "light mode",
  "accessibility",
  "internationalization",
  "localization",
  "i18n",
  "l10n",
  "translations",
  "currency formatting",
  "date formatting",
  "time zones",
  "timezone conversion",
  "locale",
  "user preferences",
  "settings",
  "notifications",
  "email notifications",
  "sms notifications",
  "push notifications",
  "web push",
  "service workers",
  "offline support",
  "pwa",
  "manifest",
  "service worker caching",
  "background sync",
  "indexeddb",
  "localstorage",
  "sessionstorage",
  "cookies",
  "authentication",
  "authorization",
  "oauth2",
  "jwt",
  "session",
  "refresh token",
  "access token",
  "roles",
  "permissions",
  "rbac",
  "abac",
  "policy based access",
  "identity provider",
  "sso",
  "ldap",
  "openid",
  "token revocation",
  "security",
  "xss",
  "csrf",
  "sql injection",
  "no sql injection",
  "command injection",
  "path traversal",
  "input validation",
  "output encoding",
  "encryption",
  "hashing",
  "rsa",
  "aes",
  "sha256",
  "md5",
  "bcrypt",
  "argon2",
  "scrypt",
  "password storage",
  "password hashing",
  "key management",
  "ssl tls",
  "https",
  "certificates",
  "pkcs",
  "csr",
  "csr signing",
  "hsts",
  "csp",
  "caching",
  "cache control",
  "etag",
  "last modified",
  "cache busting",
  "cdn",
  "cloudfront",
  "akamai",
  "fastly",
  "nginx",
  "apache",
  "varnish",
  "load balancing",
  "round robin",
  "least connections",
  "ip hash",
  "sticky sessions",
  "failover",
  "high availability",
  "replication",
  "backup",
  "restore",
  "disaster recovery",
  "monitoring",
  "alerting",
  "logging",
  "tracing",
  "opentelemetry",
  "jaeger",
  "zipkin",
  "prometheus",
  "grafana",
  "new relic",
  "datadog",
  "sentry",
  "error tracking",
  "performance tracking",
  "profiling",
  "heap profiling",
  "cpu profiling",
  "memory profiling",
  "network profiling",
  "optimization",
  "algorithm optimization",
  "code optimization",
  "db optimization",
  "indexing",
  "query optimization",
  "normalization",
  "denormalization",
  "partitioning",
  "sharding",
  "replication",
  "consistency",
  "availability",
  "partition tolerance",
  "cap theorem",
  "eventual consistency",
  "strong consistency",
  "weak consistency",
  "concurrent systems",
  "distributed systems",
  "consensus",
  "paxos",
  "raft",
  "leader election",
  "quorum",
  "vector clocks",
  "lamport clocks",
  "logical clocks",
  "time synchronization",
  "ntp",
  "clock skew",
  "fault tolerance",
  "retry policies",
  "circuit breaker",
  "rate limiting",
  "throttling",
  "debouncing",
  "caching",
  "memoization",
  "lazy evaluation",
  "load testing",
  "stress testing",
  "benchmarking",
  "profiling",
  "monitoring",
  "observability",
  "analytics",
  "data pipelines",
  "etl",
  "data engineering",
  "data warehousing",
  "big data",
  "hadoop",
  "spark",
  "flink",
  "beam",
  "airflow",
  "prefect",
  "dbt",
  "stream processing",
  "kafka",
  "rabbitmq",
  "mq",
  "pub sub",
  "queue",
  "priority queue",
  "stack",
  "heap",
  "linked list",
  "array",
  "matrix",
  "tree",
  "graph",
  "trie",
  "hashmap",
  "hashset",
  "set",
  "map",
  "dictionary",
  "queue implementation",
  "stack implementation",
  "heap implementation",
  "linked list implementation",
  "tree implementation",
  "graph implementation",
  "trie implementation",
  "segment tree implementation",
  "fenwick tree implementation",
  "disjoint set implementation",
  "union find implementation",
  "binary search",
  "ternary search",
  "exponential search",
  "interpolation search",
  "jump search",
  "sqrt decomposition",
  "mo’s algorithm",
  "sparse table",
  "kmp",
  "rabin karp",
  "z algorithm",
  "manacher",
  "suffix array",
  "suffix tree",
  "aho corasick",
  "rolling hash",
  "string matching",
  "pattern matching",
  "regex",
  "wildcard matching",
  "edit distance",
  "levenshtein distance",
  "longest common subsequence",
  "longest common substring",
  "palindromic substring",
  "palindromic subsequence",
  "longest increasing subsequence",
  "longest decreasing subsequence",
  "subsequence sum",
  "subarray sum",
  "maximum subarray",
  "minimum subarray",
  "sliding window sum",
  "sliding window max",
  "sliding window min",
  "two pointers technique",
  "meet in the middle technique",
  "divide and conquer technique",
  "greedy technique",
  "dynamic programming technique",
  "backtracking technique",
  "dfs technique",
  "bfs technique",
  "graph traversal technique",
  "tree traversal technique",
  "matrix traversal technique",
];
